name: WebUI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "NODE_VERSION=22" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Extract App Info
      run: |
        ls -la
        export app_name=$(node -p "require('./package.json').name")
        export app_version=$(node -p "require('./package.json').version")
        echo "APP_NAME=$app_name" >> $GITHUB_ENV
        echo "APP_VERSION=$app_version" >> $GITHUB_ENV

    - name: Version Info
      run: |
        echo "App Name: ${{ env.APP_NAME }}"
        echo "App Version: ${{ env.APP_VERSION }}"

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

