name: WebUI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "NODE_VERSION=22" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Extract App Info
      run: |
        export app_name=$(node -p "require('./package.json').name")
        export app_version=$(node -p "require('./package.json').version")
        echo "APP_NAME=$app_name" >> $GITHUB_ENV
        echo "APP_VERSION=$app_version" >> $GITHUB_ENV

    - name: Version Info
      run: |
        echo "App Name: ${{ env.APP_NAME }}"
        echo "App Version: ${{ env.APP_VERSION }}"
        
    - name: Build Docker image
      run: |
        docker build --build-arg APP_NAME=${{ env.APP_NAME }} -t ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }} .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}

